# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CUSUM statistics
#'
#' @param X \eqn{n\times p}, component-wise unit variances
#' @param gamma 0 = CUSUM, 0.5 = two-sample
#'
#' @return CUSUM statistics, \eqn{(n - 1)\times p\times \code{length(gamma)}}
#'
#' @export
cusum <- function(X, gamma) {
    .Call(`_DMS_cusum`, X, gamma)
}

#' Bootstrapped CUSUM statistics (two-sample version)
#'
#' @param X \eqn{n}-dimensional, unit variance
#' @param e multipliers, \eqn{n\times B}
#'
#' @return Bootstrapped CUSUM statistics, \eqn{(n - 1)\times B}
#'
cusum_2sample_boots <- function(X, e) {
    .Call(`_DMS_cusum_2sample_boots`, X, e)
}

#' Bootstrapped Max(0.5) statistics
#'
#' @param X \eqn{n\times p}
#' @param e multipliers, \eqn{n\times B}
#' @param n_boundary \code{[n_boundary:(n - n_boundary)]}
#'
#' @return Bootstrapped Max(0.5) statistics
#'
#' @references
#' Yu, M. and Chen, X. (2021) Finite Sample Change Point Inference and Identification for High-Dimensional Mean Vectors. Journal of the Royal Statistical Society Series B: Statistical Methodology, 83, 247–270
#'
#' @seealso \code{\link{YC21}}
#'
cal_YC21 <- function(X, e, n_boundary) {
    .Call(`_DMS_cal_YC21`, X, e, n_boundary)
}

#' Difference-based variance estimates
#'
#' @param X \eqn{n\times p}
#'
#' @return Component-wise variance estimates (\eqn{1\times p})
#'
#' @references
#' Rice, J. (1984). Bandwidth choice for nonparametric regression. The Annals of Statistics, 12, 1215-1230.
#'
#' @export
est_var_diff <- function(X) {
    .Call(`_DMS_est_var_diff`, X)
}

#' Normalization of Sum(0.5) statistic
#'
#' @param X \eqn{n\times p}
#'
#' @return Estimated expectation and variance of the Sum(0.5) statistic
#'
#' @references
#' Wang, Y., Zou, C., Wang, Z. and Yin, G. (2019) Multiple change-points detection in high dimension. Random Matrices: Theory and Applications, 08, 1950014.
#'
#' @seealso \code{\link{WZWY19}}
#'
cal_WZWY19 <- function(X) {
    .Call(`_DMS_cal_WZWY19`, X)
}

#' \eqn{(s_0, p)}-norm
#'
#' @param C \eqn{(n - 1)\times p}
#' @param n_boundary \code{[n_boundary:(n - n_boundary)]}
#' @param s0 \eqn{s_0}
#' @param p \eqn{p}
#'
#' @return Maximum and maximizer over all feasible changepoints for each \eqn{p}
#'
#' @references
#' Liu, B., Zhou, C., Zhang, X. and Liu, Y. (2020). A unified data-adaptive framework for high dimensional change point detection. Journal of the Royal Statistical Society: Series B (Statistical Methodology) 82 933–63.
#'
#' @seealso \code{\link{YC21}} \code{\link{cal_LZZL20}}
#'
norm_s0_p <- function(C, n_boundary, s0, p) {
    .Call(`_DMS_norm_s0_p`, C, n_boundary, s0, p)
}

#' Bootstrapped LZZL statistics
#'
#' @param X \eqn{n\times p}
#' @param e multipliers, \eqn{n\times B}
#' @param n_boundary \code{[n_boundary:(n - n_boundary)]}
#' @param s0 \eqn{s_0 = p / 2}
#' @param p \eqn{p \in \{1,2,3,4,5,\infty\}}
#' @param sig estimates of component-wise standard deviations
#'
#' @return Bootstrapped LZZL statistics
#'
#' @references
#' Liu, B., Zhou, C., Zhang, X. and Liu, Y. (2020). A unified data-adaptive framework for high dimensional change point detection. Journal of the Royal Statistical Society: Series B (Statistical Methodology) 82 933–63.
#'
#' @seealso \code{\link{YC21}} \code{\link{norm_s0_p}}
#'
cal_LZZL20 <- function(X, e, n_boundary, s0, p, sig) {
    .Call(`_DMS_cal_LZZL20`, X, e, n_boundary, s0, p, sig)
}

#' ZWS statistics
#'
#' The following implementation is an adaptation of the Matlab code created by Zhang, Wang, and Shao (2020).
#' The original Matlab code can be accessed at the following link:
#' https://doi.org/10.1080/01621459.2021.1884562.
#'
#' @param X \eqn{n\times p}
#' @param q \eqn{q \in \{2, 6\}}, suggested
#' @param truc \eqn{\code{truc} = q}
#'
#' @return ZWS statistics
#'
#' @references
#' Zhang, Y., Wang, R. and Shao, X. (2022) Adaptive Inference for Change Points in High-Dimensional Data. Journal of the American Statistical Association, 117, 1751–1762.
#'
cal_ZWS22 <- function(X, q, truc) {
    .Call(`_DMS_cal_ZWS22`, X, q, truc)
}

